### PR TITLE
Chore: Add vim settings and retab

### PR DESCRIPTION
**Pull request by wizard-28**
What it says

### CODE REVIEW

**Comment by wizard-28** [comment]
Oof what...

**Review by Henryws — APPROVED** [review]
👍🏻

**Review by D-Brox — APPROVED** [review]

**Comment by NarutoXY** [comment]
Why is test failing??

**Comment by D-Brox** [comment]
> Why is test failing??

`bc` not installed. Fix is in the main develop branch, merging into feature will probably fix the test

**Comment by wizard-28** [comment]
I'll again create this PR

**Comment by Henryws** [comment]
> > Why is test failing??
> 
> `bc` not installed. Fix is in the main develop branch, merging into feature will probably fix the test

I added this to the CI, and in repo-maintain, but it's not in the master branch

**Pull request closed without merging**
