### PR TITLE
Fix: mkdir error management

### PR DESCRIPTION
**Pull request by Zahrun**
## Purpose

image

## Approach

Silent cd error

## Progress

Done

### CODE REVIEW

**Comment by wizard-28** [comment]
Wait a second, did you get the Checklist portion in the template?

**Comment by Zahrun** [comment]
> Wait a second, did you get the Checklist portion in the template?

Yes I did.
I just thought this simple fix didn’t need a checklist

**Comment by wizard-28** [comment]
The commit style guidelines were violated I think

https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md#commits

**Comment by wizard-28** [comment]
img

See it's fixed!

**Comment by Zahrun** [comment]
I’m glad to be learning with you guys, I love this project. Thank you for your time.

**Comment by Zahrun** [comment]
Here is a proposition

https://github.com/pacstall/pacstall/pull/289/files/84592b460434a9ed92547f7ab5bb9391d29ca521..ac6615a2134999b79ced6526c186094dd33d8017

**Comment by Zahrun** [comment]
Yes, this was a little hacky. Please feel free to make a cleaner rewrite if you have an idea.
Also, I spotted that if there is a `pacdeps` in the pacscript, $SRCDIR is not cleaned after installing the pacdeps and cd ./*/ can also fail eg: `pacstall -I obs-backgroundremoval-git`

**Comment by wizard-28** [comment]
@Zahrun is this PR ready for review? Have you made all the changes you wanted?

**Comment by Zahrun** [comment]
> You should never exit on warn. Remove all the exits

I think in the case where $SRCDIR is not available, it is better to output an error message and exit. Correct me if I am wrong. In the other cases we can keep the warn and not exit.

**Pull request merged**
