### PR TITLE
feat(api): Improve color API for ANSI codes

### PR DESCRIPTION
**Pull request by D-Brox**
## Purpose
 
Current API is based on our bash implementation, that uses 4-bit ANSI codes instead of 8-bit, and doesn't take advantage of python's flexibility

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Comment by Henryws** [comment]
Fix codacy

**Comment by wizard-28** [comment]
Isn't using an existing Python library better for this task then implementing our own?

**Review by wizard-28 — CHANGES_REQUESTED** [review]
1. Fix codacy issues
2. Also explain https://github.com/pacstall/pacstall/pull/345#issuecomment-966869261

**Comment by D-Brox** [comment]
All 3 of the codacy issues are false-possitives

**Comment by D-Brox** [comment]
https://github.com/pacstall/pacstall/pull/345#issuecomment-966869261 I'm avoiding using non-standard libraries, and most libraries for ANSI either lack the style modes, are too complex or don't fill our needs

**Comment by wizard-28** [comment]
> [#345 (comment)](https://github.com/pacstall/pacstall/pull/345#issuecomment-966869261) I'm avoiding using non-standard libraries, and most libraries for ANSI either lack the style modes, are too complex or don't fill our needs

What about this? https://pypi.org/project/colored/

**Comment by wizard-28** [comment]
> > [#345 (comment)](https://github.com/pacstall/pacstall/pull/345#issuecomment-966869261) I'm avoiding using non-standard libraries, and most libraries for ANSI either lack the style modes, are too complex or don't fill our needs
> 
> What about this? https://pypi.org/project/colored/
> 
> Seems to do the job perfectly according to our requirements.

@D-Brox

**Comment by D-Brox** [comment]
Closing in favor of [colored](https://pypi.org/project/colored/)

**Pull request closed without merging**
