### PR TITLE
feat: add `suggest_solution`

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

To suggest possible solutions to problems.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Review by wizard-28 — CHANGES_REQUESTED** [review]
```bash
pacstall@ideapad:~$ pacstall -U Henryws:sds
[!] ERROR: Invalid URL
```

No suggestions for this?

**Comment by Henryws** [comment]
update.sh is self contained, so unless you want me to replicate it, we can't use it

**Review by wizard-28 — APPROVED** [review]

**Comment by D-Brox** [comment]
Better UI suggestion:
image

**Comment by D-Brox** [comment]
image

Replace with shorter equivalent link: `https://github.com/pacstall/pacstall/raw/master/pacstall`

**Comment by D-Brox** [comment]
Add suggest for `-Il` deprecation

**Comment by Henryws** [comment]
> image
> 
> Replace with shorter equivalent link: `https://github.com/pacstall/pacstall/raw/master/pacstall`

I really can't. Not unless we put the full link rewriter in `update.sh`

**Pull request merged**
