### PR TITLE
fix: remove stow, add lsb-release, fix bugs

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

To fix any bugs relating to the swap to Debs that weren't caught during the first PR.

## Fixes
* Remove warning on cleanup of non-existent pacstall keep dir 04622eba44906945a49cc7d6af7d10a57fbd03b6
* Force unzip file f71345a5962a4adbfc305545c08e8ca2efaa94a5
* Remove leftover deb after installation 59f075c2493c0733cc4c318064b4d36ded6b8082
* Get root permissions in order to get size of directory b585fa8feb9c3c385fcf60b69c816ee2ec77d889
* Move finished deb to CWD a87fd4af1398483c877b089aaf947e0cb443035f
* Log metadata after install, not before 0bc2bef3d0955dc55b4d9d02ab0c58275b28c07c
* Simplify/clean logger 573c80fef83be74b16274ac14ab5ac41ef9e5d1b
* Actually remove metadata without removescript ff7d28ef4a04e826fb5aec9c6ba46e3c10370b94
* More. Check the commits

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Comment by Henryws** [comment]
Don't merge. I need to add `createdeb` messages

**Comment by Henryws** [comment]
Ready.

**Review by wizard-28 — CHANGES_REQUESTED** [review]
# Setup

This command was used to install packages in a fresh docker environment
upgraded to your branch.

```sh
> pacstall -PI neovim-deb bemenu-git cmatrix librewolf-app
```

# UI Changes

## Don&rsquo;t show `dependencies` unnecessarily

```sh
> pacstall -Qi bemenu-git
name: bemenu-git
version: 9f46da3b
description: Dynamic menu library and client program inspired by dmenu (git release)
date installed: Tue Oct  4 09:17:18 Africa 2022
remote repo: https://github.com/pacstall/pacstall-programs
maintainer: wizard-28 <wiz28@pm.me>
dependencies: Unknown/None
install type: explicitly installed
```

I think it&rsquo;s better to not show the `dependencies` property if it&rsquo;s unknown or none.

# Bugs

## `-T`&rsquo;s inconsistencies

### First line&rsquo;s missing from the output

The first line of the output is cut-off, I suspect this is due to the way
Pacstall debs are packaged, and therefore doesn&rsquo;t require the `tail -n +2`
command to be piped.

I&rsquo;ve suggested a patch for this.

```sh
> dpkg --listfiles bemenu-git | sed -e "s/[^-][^\/]*\//  │/g" -e "s/│\([^ ]\)/│──\1/"
  /usr
  │──local
  │  │──bin
  │  │  │──bemenu
  │  │  │──bemenu-run
  │  │──include
  │  │  │──bemenu.h
  │  │──lib
  │  │  │──pkgconfig
  │  │  │  │──bemenu.pc
  │  │  │──libbemenu.so.0.6.10
  │  │  │──bemenu
  │  │  │  │──bemenu-renderer-x11.so
  │  │  │  │──bemenu-renderer-wayland.so
  │  │  │  │──bemenu-renderer-curses.so
  │  │──share
  │  │  │──man
  │  │  │  │──man1
  │  │  │  │  │──bemenu.1
  │──share
  │  │──licenses
  │  │  │──bemenu
  │  │  │  │──LICENSE-LIB
  │  │  │  │──LICENSE-CLIENT
  │  │──doc
  │  │  │──bemenu
  │  │  │  │──README.md
  │  │  │──libbemenu.so
  │  │  │──libbemenu.so.0
```

```sh
> pacstall -T bemenu-git
  │──local
  │  │──bin
  │  │  │──bemenu
  │  │  │──bemenu-run
  │  │──include
  │  │  │──bemenu.h
  │  │──lib
  │  │  │──pkgconfig
  │  │  │  │──bemenu.pc
  │  │  │──libbemenu.so.0.6.10
  │  │  │──bemenu
  │  │  │  │──bemenu-renderer-x11.so
  │  │  │  │──bemenu-renderer-wayland.so
  │  │  │  │──bemenu-renderer-curses.so
  │  │──share
  │  │  │──man
  │  │  │  │──man1
  │  │  │  │  │──bemenu.1
  │──share
  │  │──licenses
  │  │  │──bemenu
  │  │  │  │──LICENSE-LIB
  │  │  │  │──LICENSE-CLIENT
  │  │──doc
  │  │  │──bemenu
  │  │  │  │──README.md
  │  │  │──libbemenu.so
  │  │  │──libbemenu.so.0
```

### Failure for `-deb` packages

The `-T` command fails for all `-deb` packages.

```sh
> pacstall -T neovim-deb
dpkg-query: package 'neovim-deb' is not installed
Use dpkg --contents (= dpkg-deb --contents) to list archive files contents.
```

I&rsquo;ve suggested a patch for this too.

## Everything provides `nvim`

```sh
> apt show bemenu-git -a
Package: bemenu-git
Version: 9f46da3b
Status: install ok installed
Priority: optional
Section: Pacstall
Maintainer: wizard-28 <wiz28@pm.me>
Installed-Size: 911 kB
Provides: nvim # Provies `nvim` here erroneously.
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Dynamic menu library and client program inspired by dmenu (git release)
```

```sh
> apt show cmatrix -a

# --snip--

Package: cmatrix
Version: 2.0
Status: install ok installed
Priority: optional
Section: Pacstall
Maintainer: WRM-42 <y8bsbahy@anonaddy.me>
Installed-Size: 141 kB
Provides: nvim # Provies `nvim` here erroneously.
Depends: libncurses5-dev, libncursesw5-dev
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Terminal based The Matrix like implementation
```

Every package installed by that pacstall command provides `nvim` except
`neovim-deb`

# Closing remarks

I haven't tested how pacdeps are handled here, as I couldn't find a *working* pacscript with pacdeps. If you find one, do let me know!

**Comment by Henryws** [comment]
@wizard-28 I have fixed the UI change part, the erroneous gives part, and the `-T` deb part.

I am still waiting for your input on the `-T` output.

**Comment by Henryws** [comment]
`amfora-bin` works with `-T`. (side note: packages that are not `-deb` should not contain `gives`) @wizard-28

**Pull request merged**
