### PR TITLE
rm(update.sh): remove wacked apt command

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

It doesn't make sense.

## Approach

Remove it.

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Review by wizard-28 — APPROVED** [review]

**Review by D-Brox — APPROVED** [review]
It made sense for when we switched from `aria2` to `axel` tho. It's just old compatibility code by now

**Comment by Henryws** [comment]
> It made sense for when we switched from `aria2` to `axel` tho. It's just old compatibility code by now

Even then, the code would have tried to install `axel` with apt if apt didn't exist 🤷🏻

**Comment by D-Brox** [comment]
Who wrote `apt` instead of `axel`? Oh god, I hope it wasn't me

**Comment by Henryws** [comment]
> Who wrote `apt` instead of `axel`? Oh god, I hope it wasn't me

Yup, it was you -_-

**Comment by D-Brox** [comment]
'o'

**Comment by Henryws** [comment]
https://github.com/pacstall/pacstall/commit/5e8b31b3d4c40678db19121221b4d736afaaa46f#diff-b8a8c36a95f2b54886d2b665b77304c094973ba7d4dc465e634b1a0b53b933ceR36

**Pull request merged**
