### PR TITLE
Fix: Phantom Updates

### PR DESCRIPTION
**Pull request by wizard-28**

### CODE REVIEW

**Comment by wizard-28** [comment]
And as a sidenote, why are the logs all over the place, firstly, some are there in `/tmp/pacstall`, one other is in `/tmp/pacstall-up-list`, other is in `/tmp/pacstall-optdepends`?

**Review by Henryws — APPROVED** [review]
Looks good

**Comment by Henryws** [comment]
> And as a sidenote, why are the logs all over the place, firstly, some are there in `/tmp/pacstall`, one other is in `/tmp/pacstall-up-list`, other is in `/tmp/pacstall-optdepends`?

Because on is a list for upgrades, and another is for optional dependencies...

**Comment by wizard-28** [comment]
I meant where aren't they all in the `/tmp/pacstall/` directory?

**Comment by Henryws** [comment]
> I meant why aren't they all in the `/tmp/pacstall/` directory?

Because they would get deleted at possibly the wrong time

**Pull request merged**
