### PR TITLE
previous command crashes terminal when run under zsh shell

### PR DESCRIPTION
**Pull request by sanjay-kr-commit**
## Purpose

to avoid terminal crash when run under zsh shell

## Approach

it runs current command under a bash shell to avoid zsh shell crash

## Progress

- [x] Make command compatible with zsh shell

## Checklist

- [ ] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Comment by Elsie19** [comment]
Can you explain what "crashes"?

**Comment by sanjay-kr-commit** [comment]
> Can you explain what "crashes"?

Today I did a clean install of my distro but whenever I tried pasting previous command in zsh shell it kept crashing and worked under bash for some reason, although I'm not sure why, so I wrapped the command under another bash instance and it worked

**Comment by Elsie19** [comment]
You're not explaining what a crash means. Did it segfault? Did it just fail to run?

**Comment by sanjay-kr-commit** [comment]
> You're not explaining what a crash means. Did it segfault? Did it just fail to run?

**Pull request closed without merging**
