### PR TITLE
Change certain variables to readonly

### PR DESCRIPTION
**Pull request by Henryws**
this can help if a malicious pacscript attempts to change certain pacstall variables that could lead to unintentional consequences

### CODE REVIEW

**Comment by wizard-28** [comment]
> this can help if a malicious pacscript attempts to change certain pacstall variables that could lead to unintentional consequences

How would the malicious script change it hypothetically?

**Comment by Henryws** [comment]
For one, they could change the hashing variable to comply with their altered hash, so that they can install malicious software.

**Comment by wizard-28** [comment]
> For one, they could change the hashing variable to comply with their altered hash, so that they can install malicious software.

Yeah, but if they can modify the variables. Then they can also remove the `readonly` declaration, and turn the variables into whatever they want.

**Comment by Henryws** [comment]
> Yeah, but if they can modify the variables. Then they can also remove the readonly declaration, and turn the variables into whatever they want.

readonly could stop novice script kiddies. I know this won't stop seriously determined people, but it's a small addition that prevents a wider range of attacks

**Review by wizard-28 — APPROVED** [review]

**Pull request merged**
