### PR TITLE
upd(pacstall): `5.5.0` -> `6.0.0`

### PR DESCRIPTION
**Pull request by oklopfer**
I still have to update the wiki and add the how to blurb in the release notes

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Comment by Elsie19** [comment]
Don't forget the info pages!!!!

**Comment by oklopfer** [comment]
> Don't forget the info pages!!!!

You should do that then

**Comment by Elsie19** [comment]
How fast do we need 6.0.0 out?

**Comment by oklopfer** [comment]
> How fast do we need 6.0.0 out?

In the next few days preferably so we can move into beta/RC for RL

**Pull request merged**
