### PR TITLE
Feat: Add option for colorscheme change

### PR DESCRIPTION
**Pull request by NarutoXY**
# Purpose

Add option for sourcing color variables

# Approach

Check if file exists
Source the file

# Progress

Make a checklist of your progress

- [x] Add option for colorscheme change

### CODE REVIEW

**Comment by Henryws** [comment]
what would even be changed in a CLI program??

**Comment by NarutoXY** [comment]
Colors obviously

**Comment by Henryws** [comment]
where would the colors be?

**Comment by NarutoXY** [comment]
In the pacstall output

**Review by D-Brox — CHANGES_REQUESTED** [review]
Add default config file and move the configs from pacstall main script to it

**Pull request closed without merging**
