### PR TITLE
fix: miscellaneous possible bugs due to possible dashes in inputs

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

To prevent bugs because of malformed input, like a dash, which would be evaluated by bash as a flag.

## Approach

Add `--` before inputs so bash evaluates them as inputs instead of flags

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Review by wizard-28 — COMMENTED** [review]
Are you sure these are the only lines vulnerable to this kind of bug?

**Comment by Henryws** [comment]
There are more places where we *could* put them, but these are the places where a dash is possible. The ones I fixed are where the input is fluid and could contain a dash. The rest are fixed to a certain string.

**Review by wizard-28 — APPROVED** [review]
All worked, but didn't test `add-repo`

**Comment by Henryws** [comment]
> All worked, but didn't test `add-repo`

```bash
[*] WARNING: The repo link must be the root to the raw files
[*] WARNING: Make sure the repo contains a package list
Do you want to add "-" to the repo list? [y/N] y
[*] WARNING: If the URL is a private repo, edit /usr/share/pacstall/repo/pacstallrepo.txt
[!] ERROR: packagelist file not found
```

**Review by D-Brox — APPROVED** [review]

**Pull request merged**
