### PR TITLE
Remove fakeroot

### PR DESCRIPTION
**Pull request by Henryws**

### CODE REVIEW

**Comment by Henryws** [comment]
Still waiting on a review @wizard-28 @NarutoXY @D-Brox

**Review by NarutoXY — CHANGES_REQUESTED** [review]
I think fakeroot will be good for security. I and @wizard-28 were talking about on Discord and we came to the conclusion if we can disable sudo when we are in fakeroot then it will be really nice

**Comment by Henryws** [comment]
But can we?

**Comment by Henryws** [comment]
> I think fakeroot will be good for security. I and @wizard-28 were talking about on Discord and we came to the conclusion if we can disable sudo when we are in fakeroot then it will be really nice

We've talked with Hwittenborn (makedeb guy), and we've come to the conclusion that fakeroot does not suit our needs

**Comment by NarutoXY** [comment]
I guess merge this pr then

**Review by NarutoXY — APPROVED** [review]

**Comment by wizard-28** [comment]
Wait... Don't merge wait.

It's not tested yet!

**Comment by Henryws** [comment]
> It's not tested yet!

I've been using this branch for my pacstall usage for the past week. Nothing out of the ordinary

**Comment by wizard-28** [comment]
Test all the commands. `-A`, `-L` etc

**Comment by Henryws** [comment]
> Test all the commands. `-A`, `-L` etc

The only commands that were changed was the `-I` and `-Il` flags

**Review by wizard-28 — CHANGES_REQUESTED** [review]
Remove `fakeroot` dependency form `install.sh` and from the other Pacstall repos ( pacstall.deb etc repos)

**Review by wizard-28 — APPROVED** [review]
Wait for @D-Brox's review too... As this is a feature removal all 3 approvals are required.

**Review by D-Brox — APPROVED** [review]

**Pull request merged**
