### PR TITLE
Exit on download fail

### PR DESCRIPTION
**Pull request by Henryws**
## Purpose

Exit early, exit fast

## Approach

Add a check to detect if the file failed to download

## Checklist

- [x] I confirm that I have read the [contributing guidelines](https://github.com/pacstall/pacstall/blob/develop/CONTRIBUTING.md), and this pull request is abiding by all the clauses stated in the guideline.

### CODE REVIEW

**Comment by wizard-28** [comment]
I think this would be better to implement in the python version


Syncing these 3 branches is a nightmare...

**Comment by Henryws** [comment]
> I think this would be better to implement in the python version
> 
> Syncing these 3 branches is a nightmare...

We can sort out the logistics later. This is important

**Comment by wizard-28** [comment]
> > I think this would be better to implement in the python version
> > 
> > Syncing these 3 branches is a nightmare...
> 
> We can sort out the logistics later. This is important

This is not really *that* important. If it were then we would have already received a bug report about this.

**Comment by Henryws** [comment]
Well I’ve had bugs related to this. When a download somehow fails, it will continue onwards, and while we have guards in place, it looks messy to continue on after a failed download

**Comment by wizard-28** [comment]
> Well I’ve had bugs related to this. When a download somehow fails, it will continue onwards, and while we have guards in place, it looks messy to continue on after a failed download

"looks messy" doesn't make it an important bugfix. Also it's not like the user's data is being corrupted or anything. It just fails. That also rarely as the links tend to work most times...

**Pull request closed without merging**
