### PR TITLE
License things

### PR DESCRIPTION
**Pull request by wizard-28**
I added the GPLv3 logo and the boilerplate to the `readme.md`, I think we also need a `COPYING.md` file...

### CODE REVIEW

**Review by Henryws — APPROVED** [review]
looks good

**Comment by wizard-28** [comment]
What to do about the `COPYING.md` file?

**Comment by Henryws** [comment]
what about it?

**Comment by wizard-28** [comment]
From what I can see from other repos, COPYING mentions the portions of the software that were taken from another software/license + a pointer to the GPLv3 license

**Comment by Henryws** [comment]
Won't the GPL license file be enough?

**Comment by wizard-28** [comment]
Here's the official steps from GNU
img

**Comment by Henryws** [comment]
But the license is good enough. Why a copying?

**Comment by wizard-28** [comment]
`COPYING` file is useful to indicate which portions of the software were taken from other software/licenses
For example

**Comment by Henryws** [comment]
So like, I took the fancy_message from the rolling rhino script, so I would have to specify that?

**Comment by wizard-28** [comment]
Probably...
Here's some examples of COPYING
https://github.com/named-data/NFD/blob/master/COPYING.md
https://github.com/EmuZONE/OpenAGE/blob/720e107d65db8c67f1db6a4fd28a11fe3fb11cd6/copying.md

**Comment by wizard-28** [comment]
And you know that keeping the project `GPL-3.0 only` will not permit us to use future technologies that are licensed under future GPLs (If we absolutely have to use future GPL technologies we have to re-license the entire project probably as Audacity is doing xD.)

**Comment by wizard-28** [comment]
So any updates on this @Henryws, will you be adding a COPYING file?

**Comment by Henryws** [comment]
> So any updates on this @Henryws, will you be adding a COPYING file?

Yeah, just other things I have to do

**Comment by wizard-28** [comment]
Umm... well then I am merging this PR then, and I'll create a separate PR for the COPYING

**Comment by Henryws** [comment]
Sorry, pressed confused emoji accidentely

**Pull request merged**
